title: Create deployment strategy for epicstory api
createdAt: 2024-04-18 13:05
createdBy: omateusmento@gmail.com
startedAt: 2024-04-18 13:22
description: >
  Create initial deployment strategy for epicstory api using terraform, AWS ECS instances and docker
comments:
  - createdAt: 2024-04-18 14:02
    createdBy: omateusmento@gmail.com
    content: >
      I'm having some issues with regards to build a docker image for epicstory api. I'm getting an
      error and executing `npm ci` command in the Dockerfile.
  - createdAt: 2024-04-18 15:33
    createdBy: omateusmento@gmail.com
    content: >
      I was able to fix the problem in the previous comment by add command in Dockerfile to install
      python3 and other dependencies
      ```Dockerfile
      RUN apt-get update -y && apt-get install python3 make g++ -y
      ```
  - createdAt: 2024-04-18 15:35
    createdBy: omateusmento@gmail.com
    content: >
      Now I'm having a problem when running a script to build and run a docker image on ec2 instance.
      It seems to be cloning the repository and installing docker but the image is being built.
      I ssh into the instance and check that no image is built. Needs some investigation.
      Some error occurs in the ec2 user data script and I can't even see it.
  - createdAt: 2024-04-18 15:55
    createdBy: omateusmento@gmail.com
    content: >
      Another comment on the strategy I'm using is that the docker image is built and store inside a
      ec2 instance. Another option would be to build it in a CI/CD pipeline and push it to a repository.
  - createdAt: 2024-04-18 17:14
    createdBy: omateusmento@gmail.com
    content: >
      Seems that the issue having to the image not being built and run is related to the time I ssh into
      the instance. The image was still being built and have not finished yet but still the image wouldn't
      run because of the run missed a detached mode. The deployment strategy is able to build the image
      on ec2 instance and run in detached mode.
