name: Epicstory API CI/CD
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/v4
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: your_aws_region
          registry: your_aws_account_id.dkr.ecr.your_aws_region.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          docker build -t epicstory-api .
          docker tag epicstory-api ${{ steps.login-ecr.outputs.registry }}/epicstory-api
          docker push ${{ steps.login-ecr.outputs.registry }}/epicstory-api
