name: Epicstory CI/CD
on:
  push:
    branches: main
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd app
          npm ci
      - name: Run unit tests
        run: |
          cd app
          npm run test:unit
  revert-app-deploy:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Init terraform backend
        run: |
          cd app/deploy
          terraform init
      - name: Revert terraform plan
        run: |
          cd app/deploy
          terraform destroy --auto-approve \
            -var AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" \
            -var AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}" \
            -var AWS_REGISTRY="${{secrets.AWS_REGISTRY}}" \
            -var AWS_REGION="${{secrets.AWS_REGION}}"
  deploy-app:
    runs-on: ubuntu-latest
    needs: ["revert-app-deploy", "revert-api-deploy"]
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Init terraform backend
        run: |
          cd app/deploy
          terraform init
      - name: Deploy terraform plan
        run: |
          cd app/deploy
          terraform apply --auto-approve \
            -var AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" \
            -var AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}" \
            -var AWS_REGISTRY="${{secrets.AWS_REGISTRY}}" \
            -var AWS_REGION="${{secrets.AWS_REGION}}"

  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd api
          npm ci
      - name: Run unit tests
        run: |
          cd api
          npm test
  publish-api:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login Docker to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_REGISTRY }}
      - name: Build and publish docker image
        run: |
          cd api
          NODE_VERSION=$(cat .nvmrc | sed 's/^v//')
          docker build -t epicstory-api --build-arg NODE_VERSION=$NODE_VERSION .
          docker tag epicstory-api ${{ steps.login-ecr.outputs.registry }}/epicstory-api
          docker push ${{ steps.login-ecr.outputs.registry }}/epicstory-api
  revert-api-deploy:
    runs-on: ubuntu-latest
    needs: publish-api
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Deploy terraform plan
        run: |
          cd api/deploy
          terraform init
          terraform destroy --auto-approve \
            -var AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" \
            -var AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}" \
            -var AWS_REGISTRY="${{secrets.AWS_REGISTRY}}" \
            -var AWS_REGION="${{secrets.AWS_REGION}}"
  deploy-api:
    runs-on: ubuntu-latest
    needs: [revert-api-deploy, revert-app-deploy]
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Deploy terraform plan
        run: |
          cd api/deploy
          terraform init
          terraform apply --auto-approve \
            -var AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" \
            -var AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}" \
            -var AWS_REGISTRY="${{secrets.AWS_REGISTRY}}" \
            -var AWS_REGION="${{secrets.AWS_REGION}}"
